"""
F1 Historical Backfill DAG
Generated by the DAG Factory.
"""

from dags.dag_factory import create_f1_pipeline_dag
from datetime import timedelta

# Define the unique properties for the historical backfill DAG
DAG_ID = 'f1_historical_backfill'

# Define specific overrides for the backfill DAG's default arguments
backfill_default_args = {
    'email_on_failure': True,  # Send email for manual runs
    'retries': 3,              # More retries for long-running backfills
    'retry_delay': timedelta(minutes=10)
}

# Use the factory to generate the DAG
globals()[DAG_ID] = create_f1_pipeline_dag(
    dag_id=DAG_ID,
    schedule=None,  # Manual trigger only
    description='F1 2025 Season - Manual Historical Data Backfill (Generated by Factory)',
    default_args_override=backfill_default_args,
    tags=['f1', 'backfill', 'historical', 'manual']
)