"""
F1 End-to-End Pipeline DAG
Generated by the DAG Factory.
"""

from dags.dag_factory import create_f1_pipeline_dag

# Define the unique properties for the end-to-end pipeline DAG
DAG_ID = 'f1_end_to_end_pipeline'

# Use the factory to generate the DAG
# The globals() dictionary is used to dynamically add the generated DAG to the Airflow namespace
globals()[DAG_ID] = create_f1_pipeline_dag(
    dag_id=DAG_ID,
    schedule='0 6 * * 1',  # Weekly Monday 6 AM
    description='F1 Complete Pipeline: API → Bronze → Silver → Gold (Generated by Factory)',
    tags=['f1', 'end-to-end', 'medallion-architecture']
)